# Generated by Django 5.0.6 on 2024-06-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0003_alter_carlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='chasisNumber',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
